name: length
description: A terrible esolang
version: 0.2.0
repository: https://github.com/nailuj29gaming/length
# homepage: https://www.example.com
environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies:
  args: ^1.6.0
  stack: ^0.1.3
